import type { Metadata } from "next";
// import localFont from "next/font/local";
// import {Inter} from "next/font/google"
import {Aladin} from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// const inter = Inter({subsets: ["latin"], variable: "--font-sans"});
const aladin = Aladin({
  subsets: ["latin"], variable: "--font-aladin-sans",
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen font-sans antialiased",aladin.variable)}>
        {children}
      </body>
    </html>
  );
}

//default code that was there.
{/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}